# Welcome to Serverless!

service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

  # you can add packaging information here
package:
  include: src

plugins:
  - serverless-plugin-typescript

functions:
  cost:
    role: costFunctionPermission
    handler: src/handler.cost
    events:
      - http:
          path: /
          method: get

resources:
  Resources:
    costFunctionPermission:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: costFunctionPermission # required if you want to use 'serverless deploy --function' later on
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: costFunctionPermission
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "ce:GetCostAndUsage"
                  Resource: "*"
                - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "log-group:/aws/lambda/*:*:*"
